/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador;

import javax.swing.JOptionPane;

/**
 *
 * @author nemea
 */
public class Interfaz extends javax.swing.JFrame {

    static void setTexto2(String texto) {
        JOptionPane.showMessageDialog(null, texto);
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_escanear = new javax.swing.JButton();
        jlbl_codigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxta_codigo = new javax.swing.JTextArea();
        jlbl_tlines = new javax.swing.JLabel();
        jtxtf_tlineas = new javax.swing.JTextField();
        jlbl_tpalabras = new javax.swing.JLabel();
        jtxtf_tpalabras = new javax.swing.JTextField();
        jbtn_intermedio = new javax.swing.JButton();
        jbtn_ensamblar = new javax.swing.JButton();
        jbtn_objeto = new javax.swing.JButton();
        jbtn_ejecutable = new javax.swing.JButton();
        jbtn_ejecutar = new javax.swing.JButton();
        jbtn_limpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxta_codigo1 = new javax.swing.JTextArea();
        jlbl_codigosalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_escanear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/search.png"))); // NOI18N
        jbtn_escanear.setText("Escanear");

        jlbl_codigo.setText("Codigo:");

        jtxta_codigo.setColumns(20);
        jtxta_codigo.setRows(5);
        jScrollPane1.setViewportView(jtxta_codigo);

        jlbl_tlines.setText("Total de lineas:");

        jtxtf_tlineas.setText("0");

        jlbl_tpalabras.setText("Toral de palabras:");

        jtxtf_tpalabras.setText("0");

        jbtn_intermedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/layers.png"))); // NOI18N
        jbtn_intermedio.setText("Intermedio");

        jbtn_ensamblar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/settings-1.png"))); // NOI18N
        jbtn_ensamblar.setText("Ensamblar");

        jbtn_objeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/record.png"))); // NOI18N
        jbtn_objeto.setText("Objeto");

        jbtn_ejecutable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/box.png"))); // NOI18N
        jbtn_ejecutable.setText("Ejecutable");

        jbtn_ejecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/next.png"))); // NOI18N
        jbtn_ejecutar.setText("Ejecutar");

        jbtn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/page.png"))); // NOI18N
        jbtn_limpiar.setText("Limpiar");

        jtxta_codigo1.setColumns(20);
        jtxta_codigo1.setRows(5);
        jScrollPane2.setViewportView(jtxta_codigo1);

        jlbl_codigosalida.setText("Codigo salida:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbl_tlines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtf_tlineas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_tpalabras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtf_tpalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_codigo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn_escanear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_intermedio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jbtn_ensamblar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_objeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_ejecutable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_ejecutar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jlbl_codigosalida)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbtn_escanear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbl_codigo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_intermedio)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_ensamblar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_objeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_ejecutable)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_ejecutar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_limpiar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_tlines)
                    .addComponent(jtxtf_tlineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_tpalabras)
                    .addComponent(jtxtf_tpalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlbl_codigosalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_ejecutable;
    private javax.swing.JButton jbtn_ejecutar;
    private javax.swing.JButton jbtn_ensamblar;
    private javax.swing.JButton jbtn_escanear;
    private javax.swing.JButton jbtn_intermedio;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JButton jbtn_objeto;
    private javax.swing.JLabel jlbl_codigo;
    private javax.swing.JLabel jlbl_codigosalida;
    private javax.swing.JLabel jlbl_tlines;
    private javax.swing.JLabel jlbl_tpalabras;
    private javax.swing.JTextArea jtxta_codigo;
    private javax.swing.JTextArea jtxta_codigo1;
    private javax.swing.JTextField jtxtf_tlineas;
    private javax.swing.JTextField jtxtf_tpalabras;
    // End of variables declaration//GEN-END:variables
}
