/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;
//import java_cup.Main; // esta es la que me genera el error de main() private por que intentaba acceder a otra clase gemela
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.FileNotFoundException; // por si las dudas..

/**
 *
 * @author nemea
 */
public class Interfaz extends javax.swing.JFrame {

    /*
    static void setTexto2(String texto) {
        JOptionPane.showMessageDialog(null, texto);
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*
    /

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_escanear = new javax.swing.JButton();
        jlbl_codigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxta_codigo = new javax.swing.JTextArea();
        jlbl_tlines = new javax.swing.JLabel();
        jtxtf_tlineas = new javax.swing.JTextField();
        jlbl_tpalabras = new javax.swing.JLabel();
        jtxtf_tpalabras = new javax.swing.JTextField();
        jbtn_intermedio = new javax.swing.JButton();
        jbtn_ensamblar = new javax.swing.JButton();
        jbtn_objeto = new javax.swing.JButton();
        jbtn_ejecutable = new javax.swing.JButton();
        jbtn_ejecutar = new javax.swing.JButton();
        jbtn_limpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxta_codigo1 = new javax.swing.JTextArea();
        jlbl_codigosalida = new javax.swing.JLabel();
        jbtn_abrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_escanear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/search.png"))); // NOI18N
        jbtn_escanear.setText("Escanear");
        jbtn_escanear.setDisabledIcon(null);
        jbtn_escanear.setDisabledSelectedIcon(null);
        jbtn_escanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_escanearActionPerformed(evt);
            }
        });

        jlbl_codigo.setText("Codigo:");

        jtxta_codigo.setColumns(20);
        jtxta_codigo.setRows(5);
        jScrollPane1.setViewportView(jtxta_codigo);

        jlbl_tlines.setText("Total de lineas:");

        jtxtf_tlineas.setText("0");

        jlbl_tpalabras.setText("Toral de palabras:");

        jtxtf_tpalabras.setText("0");

        jbtn_intermedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/layers.png"))); // NOI18N
        jbtn_intermedio.setText("Intermedio");
        jbtn_intermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_intermedioActionPerformed(evt);
            }
        });

        jbtn_ensamblar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/settings-1.png"))); // NOI18N
        jbtn_ensamblar.setText("Ensamblar");
        jbtn_ensamblar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ensamblarActionPerformed(evt);
            }
        });

        jbtn_objeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/record.png"))); // NOI18N
        jbtn_objeto.setText("Objeto");
        jbtn_objeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_objetoActionPerformed(evt);
            }
        });

        jbtn_ejecutable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/box.png"))); // NOI18N
        jbtn_ejecutable.setText("Ejecutable");
        jbtn_ejecutable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ejecutableActionPerformed(evt);
            }
        });

        jbtn_ejecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/next.png"))); // NOI18N
        jbtn_ejecutar.setText("Ejecutar");
        jbtn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ejecutarActionPerformed(evt);
            }
        });

        jbtn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/page.png"))); // NOI18N
        jbtn_limpiar.setText("Limpiar");
        jbtn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarActionPerformed(evt);
            }
        });

        jtxta_codigo1.setColumns(20);
        jtxta_codigo1.setRows(5);
        jScrollPane2.setViewportView(jtxta_codigo1);

        jlbl_codigosalida.setText("Codigo salida:");

        jbtn_abrir.setText("Abrir ..");
        jbtn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_abrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlbl_tlines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtf_tlineas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_tpalabras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtf_tpalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_codigo))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbtn_abrir)
                                .addGap(195, 195, 195)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn_escanear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_intermedio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jbtn_ensamblar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_objeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_ejecutable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_ejecutar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jlbl_codigosalida)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbtn_escanear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn_abrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbl_codigo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_intermedio)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_ensamblar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_objeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_ejecutable)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_ejecutar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_limpiar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_tlines)
                    .addComponent(jtxtf_tlineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_tpalabras)
                    .addComponent(jtxtf_tpalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlbl_codigosalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_abrirActionPerformed
        
// TODO add your handling code here:
        String aux="";
        String texto="";
        String total="";
        String mostrar="";
        String palabritas="";
        int palabras=0;
        int confil=0;
        int palabrasaux=0;
        try{
       
            JFileChooser file =new JFileChooser();//// qui se elige el archivo
            file.showOpenDialog(this);
            
            
                    File abre = file.getSelectedFile(); //variable archivo  obtener datos
                    if(abre!=null){/////////////////   si es distinto de vacio  que  entre 
                        FileReader archivos =new FileReader(abre);
                        BufferedReader lee =new BufferedReader(archivos);///  variable  para  leer  archivo 

                        while((aux=lee.readLine())!=null){ //mientras que la linea  no encuentre  un vacio 
                            palabrasaux=0;

                         StringTokenizer st =new StringTokenizer(aux);    ////   creanfdo el token
                         while (st.hasMoreTokens()){  ////
                         //   System.out.println(st.nextToken(" "));
                         st.nextToken(" ");
                         palabras++;  // PALABRAS ? 
                         palabrasaux++; // LINEAS??
                          //  System.out.println("total de palabras "+palabras);
                    }
                 // totalPala+=palabras; 
                 //   totalPala+=palabrasaux;   
                   texto+= aux+ "\n";
                   confil++;
                   total=confil+"";
                   palabritas=palabras+"";
                   // palabritas=palabrasaux+"";
                 mostrar =mostrar +="\n  fila "+confil+" contiene          " +palabrasaux+" palabras ";
            }
             lee.close();                    
            }
        }
         catch(IOException ex)
        {
            JOptionPane.showMessageDialog(null, ex+"" +"\n no se ha encontrado el arechivo ","advertencia", JOptionPane.WARNING_MESSAGE);
        }
        //txt_MOSTRARLINEAS.setText("\n"+mostrar);
        //jlbl_codigo.setText(texto);
        jtxta_codigo.setText(texto);
        jtxtf_tlineas.setText(total);
        jtxtf_tpalabras.setText(palabritas);
    }//GEN-LAST:event_jbtn_abrirActionPerformed

    private void jbtn_escanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_escanearActionPerformed
    guardar();
    new Main();
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_escanearActionPerformed

    private void jbtn_intermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_intermedioActionPerformed
try 
	{
            String [] cmd = {"intermedio.bat"}; 
            Runtime.getRuntime().exec(cmd);
            
           JOptionPane.showMessageDialog(null,"Codigo intermedio realizado exitosamente!!!");
            System.out.println("Codigo intermedio realizado exitosamente!!!");
	} 
     catch (IOException ioe)
	{
	System.out.println (ioe);
	}        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_intermedioActionPerformed

    private void jbtn_ensamblarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ensamblarActionPerformed
try 
	{
            String [] cmd = {"ensamblador.bat"}; 
            Runtime.getRuntime().exec(cmd);
            JOptionPane.showMessageDialog(null,"Codigo Ensamblador realizado exitosamente!!!");
            System.out.println("Codigo Ensamblador realizado exitosamente!!!");
	} 
     catch (IOException ioe)
	{
	System.out.println (ioe);
	}        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_ensamblarActionPerformed

    private void jbtn_objetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_objetoActionPerformed
try 
	{
            String [] cmd = {"objeto.bat"}; 
            Runtime.getRuntime().exec(cmd);
            JOptionPane.showMessageDialog(null,"Codigo Objeto realizado exitosamente!!!");
            System.out.println("Codigo Objeto realizado exitosamente!!!");
	} 
     catch (IOException ioe)
	{
	System.out.println (ioe);
	}        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_objetoActionPerformed

    private void jbtn_ejecutableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ejecutableActionPerformed
try 
	{
            String [] cmd = {"ejecutable.bat"}; 
            Runtime.getRuntime().exec(cmd);
            JOptionPane.showMessageDialog(null,"Codigo Ejecutable realizado exitosamente!!!");
            System.out.println("Codigo Ejecutable realizado exitosamente!!!");
	} 
     catch (IOException ioe)
	{
	System.out.println (ioe);
	}          
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_ejecutableActionPerformed

    private void jbtn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ejecutarActionPerformed
    try 
	{
            String [] cmd = {"correr.bat"}; 
            Runtime.getRuntime().exec(cmd);
            JOptionPane.showMessageDialog(null,"Ejecutando Programa");
            System.out.println("Ejecutando Programa");
	} 
     catch (IOException ioe)
	{
	System.out.println (ioe);
	}  
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_ejecutarActionPerformed

    private void jbtn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarActionPerformed
jtxta_codigo.setText(null);
jtxta_codigo1.setText("");        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_abrir;
    private javax.swing.JButton jbtn_ejecutable;
    private javax.swing.JButton jbtn_ejecutar;
    private javax.swing.JButton jbtn_ensamblar;
    private javax.swing.JButton jbtn_escanear;
    private javax.swing.JButton jbtn_intermedio;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JButton jbtn_objeto;
    private javax.swing.JLabel jlbl_codigo;
    private javax.swing.JLabel jlbl_codigosalida;
    private javax.swing.JLabel jlbl_tlines;
    private javax.swing.JLabel jlbl_tpalabras;
    public static javax.swing.JTextArea jtxta_codigo;
    public static javax.swing.JTextArea jtxta_codigo1;
    private javax.swing.JTextField jtxtf_tlineas;
    private javax.swing.JTextField jtxtf_tpalabras;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
         String uno=new String();
uno=jtxta_codigo.getText();
try {
File file1 = new File("entrada.cpp");
BufferedWriter output = new BufferedWriter(new FileWriter(file1));
output.write(uno);
output.close();
}
catch(Exception e) {
JOptionPane.showMessageDialog(null, "No se pudo guardar archivo de entrada debido a "+ e.toString());
}
          
    }
   
    protected static void setTexto(String name){
     jtxta_codigo.setText(jtxta_codigo.getText()+name+"\n");
    }  

    protected static void setTexto2(String name){
     jtxta_codigo1.setText( jtxta_codigo1.getText()+name+"\n");
    }

}
