/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador;
import java.awt.AWTException;
import java.awt.Robot; // prueba para delays
import java.awt.event.KeyEvent;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;
//import java_cup.Main; // esta es la que me genera el error de main() private por que intentaba acceder a otra clase gemela
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.FileNotFoundException; // por si las dudas..
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nemea
 */
public class Interfaz extends javax.swing.JFrame {

    /*
    static void setTexto2(String texto) {
        JOptionPane.showMessageDialog(null, texto);
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*
    /

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_escanear = new javax.swing.JButton();
        jlbl_codigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxta_codigo = new javax.swing.JTextArea();
        jlbl_tlines = new javax.swing.JLabel();
        jtxtf_tlineas = new javax.swing.JTextField();
        jlbl_tpalabras = new javax.swing.JLabel();
        jtxtf_tpalabras = new javax.swing.JTextField();
        jbtn_intermedio = new javax.swing.JButton();
        jbtn_ensamblar = new javax.swing.JButton();
        jbtn_objeto = new javax.swing.JButton();
        jbtn_ejecutable = new javax.swing.JButton();
        jbtn_ejecutar = new javax.swing.JButton();
        jbtn_limpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxta_codigo1 = new javax.swing.JTextArea();
        jlbl_codigosalida = new javax.swing.JLabel();
        jbtn_abrir = new javax.swing.JButton();
        jbtn_playAll = new javax.swing.JButton();
        jlbl_estatus = new javax.swing.JLabel();
        jlbl_estatusMensaje = new javax.swing.JLabel();
        jlbl_stEscanear = new javax.swing.JLabel();
        jlbl_stIntermedio = new javax.swing.JLabel();
        jlbl_stEnsamblar = new javax.swing.JLabel();
        jlbl_stObjeto = new javax.swing.JLabel();
        jlbl_stEjecutable = new javax.swing.JLabel();
        jlbl_stEjecutar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jbtn_escanear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/search.png"))); // NOI18N
        jbtn_escanear.setText("Escanear");
        jbtn_escanear.setDisabledIcon(null);
        jbtn_escanear.setDisabledSelectedIcon(null);
        jbtn_escanear.setEnabled(false);
        jbtn_escanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_escanearActionPerformed(evt);
            }
        });

        jlbl_codigo.setText("Codigo:");

        jtxta_codigo.setColumns(20);
        jtxta_codigo.setRows(5);
        jtxta_codigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtxta_codigoCaretUpdate(evt);
            }
        });
        jtxta_codigo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtxta_codigoInputMethodTextChanged(evt);
            }
        });
        jtxta_codigo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtxta_codigoPropertyChange(evt);
            }
        });
        jtxta_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxta_codigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxta_codigoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtxta_codigo);

        jlbl_tlines.setText("Total de lineas:");

        jtxtf_tlineas.setText("0");
        jtxtf_tlineas.setEnabled(false);

        jlbl_tpalabras.setText("Total de palabras:");

        jtxtf_tpalabras.setText("0");
        jtxtf_tpalabras.setEnabled(false);

        jbtn_intermedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/layers.png"))); // NOI18N
        jbtn_intermedio.setText("Intermedio");
        jbtn_intermedio.setEnabled(false);
        jbtn_intermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_intermedioActionPerformed(evt);
            }
        });

        jbtn_ensamblar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/settings-1.png"))); // NOI18N
        jbtn_ensamblar.setText("Ensamblar");
        jbtn_ensamblar.setEnabled(false);
        jbtn_ensamblar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ensamblarActionPerformed(evt);
            }
        });

        jbtn_objeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/record.png"))); // NOI18N
        jbtn_objeto.setText("Objeto");
        jbtn_objeto.setEnabled(false);
        jbtn_objeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_objetoActionPerformed(evt);
            }
        });

        jbtn_ejecutable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/box.png"))); // NOI18N
        jbtn_ejecutable.setText("Ejecutable");
        jbtn_ejecutable.setEnabled(false);
        jbtn_ejecutable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ejecutableActionPerformed(evt);
            }
        });

        jbtn_ejecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/next.png"))); // NOI18N
        jbtn_ejecutar.setText("Ejecutar");
        jbtn_ejecutar.setEnabled(false);
        jbtn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ejecutarActionPerformed(evt);
            }
        });

        jbtn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png36/page.png"))); // NOI18N
        jbtn_limpiar.setText("Limpiar");
        jbtn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarActionPerformed(evt);
            }
        });

        jtxta_codigo1.setColumns(20);
        jtxta_codigo1.setRows(5);
        jtxta_codigo1.setEnabled(false);
        jScrollPane2.setViewportView(jtxta_codigo1);

        jlbl_codigosalida.setText("Codigo salida:");

        jbtn_abrir.setText("Abrir ..");
        jbtn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_abrirActionPerformed(evt);
            }
        });

        jbtn_playAll.setText("Vamo a compila..");
        jbtn_playAll.setEnabled(false);
        jbtn_playAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_playAllActionPerformed(evt);
            }
        });

        jlbl_estatus.setText("Estatus:");

        jlbl_estatusMensaje.setText("esperando...");

        jlbl_stEscanear.setText("ERROR");

        jlbl_stIntermedio.setText("ERROR");

        jlbl_stEnsamblar.setText("ERROR");

        jlbl_stObjeto.setText("ERROR");

        jlbl_stEjecutable.setText("ERROR");

        jlbl_stEjecutar.setText("ERROR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbl_codigo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbl_stIntermedio, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jlbl_stEnsamblar)
                                                .addGap(4, 4, 4))
                                            .addComponent(jlbl_stObjeto, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlbl_stEjecutable, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlbl_stEjecutar, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbtn_abrir)
                                .addGap(48, 48, 48)
                                .addComponent(jbtn_playAll)
                                .addGap(63, 63, 63)
                                .addComponent(jlbl_stEscanear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn_escanear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_intermedio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jbtn_ensamblar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_objeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_ejecutable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_ejecutar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jlbl_codigosalida))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlbl_tlines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtf_tlineas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_tpalabras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtf_tpalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbl_estatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbl_estatusMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_abrir)
                            .addComponent(jbtn_playAll))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_codigo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_escanear)
                            .addComponent(jlbl_stEscanear, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_intermedio)
                            .addComponent(jlbl_stIntermedio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_ensamblar)
                            .addComponent(jlbl_stEnsamblar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_objeto)
                            .addComponent(jlbl_stObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_ejecutable)
                            .addComponent(jlbl_stEjecutable, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_ejecutar)
                            .addComponent(jlbl_stEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_limpiar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_tlines)
                            .addComponent(jtxtf_tlineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_tpalabras)
                            .addComponent(jtxtf_tpalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_estatus)
                            .addComponent(jlbl_estatusMensaje))
                        .addGap(11, 11, 11))))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlbl_codigosalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_abrirActionPerformed
        
// TODO add your handling code here:
        String aux="";
        String texto="";
        String total="";
        String mostrar="";
        String palabritas="";
        int palabras=0;
        int confil=0;
        int palabrasaux=0;
        try{
       
            JFileChooser file =new JFileChooser();//// qui se elige el archivo
            file.showOpenDialog(this);
            
            
                    File abre = file.getSelectedFile(); //variable archivo  obtener datos
                    if(abre!=null){/////////////////   si es distinto de vacio  que  entre 
                        FileReader archivos =new FileReader(abre);
                        BufferedReader lee =new BufferedReader(archivos);///  variable  para  leer  archivo 

                        while((aux=lee.readLine())!=null){ //mientras que la linea  no encuentre  un vacio 
                            palabrasaux=0;

                         StringTokenizer st =new StringTokenizer(aux);    ////   creanfdo el token
                         while (st.hasMoreTokens()){  ////
                         //   System.out.println(st.nextToken(" "));
                         st.nextToken(" ");
                         palabras++;  // PALABRAS ? 
                         palabrasaux++; // LINEAS??
                          //  System.out.println("total de palabras "+palabras);
                    }
                 // totalPala+=palabras; 
                 //   totalPala+=palabrasaux;   
                   texto+= aux+ "\n";
                   confil++;
                   total=confil+"";
                   palabritas=palabras+"";
                   // palabritas=palabrasaux+"";
                 mostrar =mostrar +="\n  fila "+confil+" contiene          " +palabrasaux+" palabras ";
            }
             lee.close();                    
            }
        }
         catch(IOException ex)
        {
            JOptionPane.showMessageDialog(null, ex+"" +"\n no se ha encontrado el arechivo ","advertencia", JOptionPane.WARNING_MESSAGE);
        }
        //txt_MOSTRARLINEAS.setText("\n"+mostrar);
        //jlbl_codigo.setText(texto);
        jtxta_codigo.setText(texto);
        libera_comandos();
        jlbl_estatusMensaje.setText("Archivo cargado con exito..");
        jtxtf_tlineas.setText(total);
        jtxtf_tpalabras.setText(palabritas);
    }//GEN-LAST:event_jbtn_abrirActionPerformed

    private void jbtn_escanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_escanearActionPerformed
    guardar();
    new Main();
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_escanearActionPerformed

    private void jbtn_intermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_intermedioActionPerformed
try 
	{
            String [] cmd = {"intermedio.bat"}; 
            Runtime.getRuntime().exec(cmd);
            
           JOptionPane.showMessageDialog(null,"Codigo intermedio realizado exitosamente!!!");
            System.out.println("Codigo intermedio realizado exitosamente!!!");
	} 
     catch (IOException ioe)
	{
	System.out.println (ioe);
	}        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_intermedioActionPerformed

    private void jbtn_ensamblarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ensamblarActionPerformed
try 
	{
            String [] cmd = {"ensamblador.bat"}; 
            Runtime.getRuntime().exec(cmd);
            JOptionPane.showMessageDialog(null,"Codigo Ensamblador realizado exitosamente!!!");
            System.out.println("Codigo Ensamblador realizado exitosamente!!!");
	} 
     catch (IOException ioe)
	{
	System.out.println (ioe);
	}        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_ensamblarActionPerformed

    private void jbtn_objetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_objetoActionPerformed
try 
	{
            String [] cmd = {"objeto.bat"}; 
            Runtime.getRuntime().exec(cmd);
            JOptionPane.showMessageDialog(null,"Codigo Objeto realizado exitosamente!!!");
            System.out.println("Codigo Objeto realizado exitosamente!!!");
	} 
     catch (IOException ioe)
	{
	System.out.println (ioe);
	}        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_objetoActionPerformed

    private void jbtn_ejecutableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ejecutableActionPerformed
try 
	{
            String [] cmd = {"ejecutable.bat"}; 
            Runtime.getRuntime().exec(cmd);
            JOptionPane.showMessageDialog(null,"Codigo Ejecutable realizado exitosamente!!!");
            System.out.println("Codigo Ejecutable realizado exitosamente!!!");
	} 
     catch (IOException ioe)
	{
	System.out.println (ioe);
	}          
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_ejecutableActionPerformed

    private void jbtn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ejecutarActionPerformed
    try 
	{
            String [] cmd = {"correr.bat"}; 
            Runtime.getRuntime().exec(cmd);
            JOptionPane.showMessageDialog(null,"Ejecutando Programa");
            System.out.println("Ejecutando Programa");
	} 
     catch (IOException ioe)
	{
	System.out.println (ioe);
	}  
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_ejecutarActionPerformed

    private void jbtn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarActionPerformed
jtxta_codigo.setText(null);
jtxta_codigo1.setText("");        
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_limpiarActionPerformed

    private void jbtn_playAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_playAllActionPerformed
   delaySleep(1000);
        jbtn_escanearActionPerformed(evt);   
   delaySleep(1000);
        jbtn_intermedioActionPerformed(evt);
   delaySleep(1500);
        jbtn_ensamblarActionPerformed(evt);
   delaySleep(1500);
        jbtn_objetoActionPerformed(evt);
   delaySleep(1500);
        jbtn_ejecutableActionPerformed(evt);
   delaySleep(2500);     
        jbtn_ejecutarActionPerformed(evt);
//////////////////////------------------------
     /*
    try {
             
            Robot robot = new Robot();
            // Creates the delay of 5 sec so that you can open notepad before
            // Robot start writting
            robot.delay(5000);
            robot.keyPress(KeyEvent.VK_H);
            robot.keyPress(KeyEvent.VK_I);
            robot.keyPress(KeyEvent.VK_SPACE);
            robot.keyPress(KeyEvent.VK_B);
            robot.keyPress(KeyEvent.VK_U);
            robot.keyPress(KeyEvent.VK_D);
            robot.keyPress(KeyEvent.VK_Y);
             
        } catch (AWTException e) {
            e.printStackTrace();
        }
     */
    //////////////////////------------------------
        //jbtn_escanearActionPerformed(evt);  // si abre el boton desde aca
        

//TimeUnit.SECONDS.sleep(1);
    /*
    try {
    Thread.sleep(1000);
} catch(InterruptedException ex) {
    Thread.currentThread().interrupt();
}
    */
    /*    
    try {
            sleep(1000);

        } catch (InterruptedException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    */
    //////////
    }//GEN-LAST:event_jbtn_playAllActionPerformed

    private void jtxta_codigoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtxta_codigoInputMethodTextChanged

// TODO add your handling code here:
    }//GEN-LAST:event_jtxta_codigoInputMethodTextChanged

    private void jtxta_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxta_codigoKeyPressed
 
// TODO add your handling code here:
    }//GEN-LAST:event_jtxta_codigoKeyPressed

    private void jtxta_codigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxta_codigoKeyReleased
 if (jtxta_codigo.getText().length()==0){
        bloqueobloqueobloqueo();
        jlbl_estatusMensaje.setText("esperando..");
    }else{
                libera_comandos();
                jlbl_estatusMensaje.setText("observando..");
    }   
        /*
        if (jtxta_codigo.getText().length()==0){
    bloquedobloqueobloqueo();
        System.out.println("blokeado");
    }else{
                libera_comandos();
    }           // TODO add your handling code here:
        */
    }//GEN-LAST:event_jtxta_codigoKeyReleased

    private void jtxta_codigoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtxta_codigoPropertyChange
    /*if (jtxta_codigo.getText().length()==0){
        bloqueobloqueobloqueo();
    }else{
                libera_comandos();
        
    }   
      */  
// TODO add your handling code here:
    }//GEN-LAST:event_jtxta_codigoPropertyChange

    private void jtxta_codigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtxta_codigoCaretUpdate
    /*
        if (jtxta_codigo.getText().length()==0){
        bloqueobloqueobloqueo();
    }else{
                libera_comandos();
        
    }   
        */
// TODO add your handling code here:
    }//GEN-LAST:event_jtxta_codigoCaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jlbl_stEscanear.setVisible(false);
        jlbl_stIntermedio.setVisible(false);
        jlbl_stEnsamblar.setVisible(false);
        jlbl_stObjeto.setVisible(false);
        jlbl_stEjecutable.setVisible(false);
        jlbl_stEjecutar.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_abrir;
    private javax.swing.JButton jbtn_ejecutable;
    private javax.swing.JButton jbtn_ejecutar;
    private javax.swing.JButton jbtn_ensamblar;
    private javax.swing.JButton jbtn_escanear;
    private javax.swing.JButton jbtn_intermedio;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JButton jbtn_objeto;
    private javax.swing.JButton jbtn_playAll;
    private javax.swing.JLabel jlbl_codigo;
    private javax.swing.JLabel jlbl_codigosalida;
    private javax.swing.JLabel jlbl_estatus;
    private static javax.swing.JLabel jlbl_estatusMensaje;
    protected static javax.swing.JLabel jlbl_stEjecutable;
    protected static javax.swing.JLabel jlbl_stEjecutar;
    protected static javax.swing.JLabel jlbl_stEnsamblar;
    protected static javax.swing.JLabel jlbl_stEscanear;
    protected static javax.swing.JLabel jlbl_stIntermedio;
    protected static javax.swing.JLabel jlbl_stObjeto;
    private javax.swing.JLabel jlbl_tlines;
    private javax.swing.JLabel jlbl_tpalabras;
    public static javax.swing.JTextArea jtxta_codigo;
    public static javax.swing.JTextArea jtxta_codigo1;
    private javax.swing.JTextField jtxtf_tlineas;
    private javax.swing.JTextField jtxtf_tpalabras;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
         String uno=new String();
uno=jtxta_codigo.getText();
try {
File file1 = new File("entrada.cpp");
BufferedWriter output = new BufferedWriter(new FileWriter(file1));
output.write(uno);
output.close();
}
catch(Exception e) {
  Interfaz.setEstatusMensaje("No se pudo guardar archivo de entrada debido a ", 1);  
JOptionPane.showMessageDialog(null, "No se pudo guardar archivo de entrada debido a "+ e.toString());
}
          
    }
   
    protected static void setTexto(String name){
     jtxta_codigo.setText(jtxta_codigo.getText()+name+"\n");
    }  

    protected static void setTexto2(String name){
     jtxta_codigo1.setText( jtxta_codigo1.getText()+name+"\n");
    }
    
    protected static void setEstatusMensaje(String texto,Integer modo){
//        jlbl_estatusMensaje.setText(texto);
        if (modo==1){ // 1 para error
            jlbl_estatusMensaje.setText(texto);
            jlbl_estatusMensaje.setBackground(java.awt.Color.red);
            jlbl_estatusMensaje.setOpaque(true);
            jlbl_estatusMensaje.setForeground(java.awt.Color.white);
        }
        if (modo==2){ // 2 para ok
            jlbl_estatusMensaje.setText(texto);
            jlbl_estatusMensaje.setBackground(java.awt.Color.green);
            jlbl_estatusMensaje.setOpaque(true);
            jlbl_estatusMensaje.setForeground(java.awt.Color.black);
        }
    }

    private void delaySleep(int i) {
     try {
    Thread.sleep(i);
        } catch(InterruptedException ex) {
    Thread.currentThread().interrupt();
}    
    }

    private void bloqueobloqueobloqueo() {
        jbtn_escanear.setEnabled(false);
                jbtn_intermedio.setEnabled(false);
                jbtn_ensamblar.setEnabled(false);
                jbtn_objeto.setEnabled(false);
                jbtn_ejecutable.setEnabled(false);
                jbtn_ejecutar.setEnabled(false);
                jbtn_playAll.setEnabled(false);
    }

    private void libera_comandos() {
         jbtn_escanear.setEnabled(true);
                jbtn_intermedio.setEnabled(true);
                jbtn_ensamblar.setEnabled(true);
                jbtn_objeto.setEnabled(true);
                jbtn_ejecutable.setEnabled(true);
                jbtn_ejecutar.setEnabled(true);
                jbtn_playAll.setEnabled(true);
    }

}
